# Nixpacks configuration for Railway deployment
# This ensures yt-dlp, ffmpeg, and Python are available

[providers]
nodejs = "18"

[phases.setup]
aptPkgs = ["ffmpeg", "python3", "python3-pip", "curl"]

[phases.install]
cmds = [
  "npm ci",
  "pip3 install --break-system-packages yt-dlp"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 