# Nixpacks configuration for Railway deployment

[phases.setup]
# System and build dependencies (canvas, ffmpeg)
apkPkgs = [
  "ffmpeg",
  "curl",
  "build-base",
  "cairo-dev",
  "pango-dev",
  "python3",
  "py3-pip",
  "libjpeg-turbo-dev",
  "giflib-dev",
  "pixman-dev",
  "pkgconf"
]

# The same packages for Debian/Ubuntu images
aptPkgs = [
  "ffmpeg",
  "curl",
  "python3",
  "python3-pip",
  "python-is-python3", # provides /usr/bin/python symlink
  "build-essential",
  "libcairo2-dev",
  "libpango1.0-dev",
  "libjpeg-dev",
  "libgif-dev",
  "libpixman-1-dev",
  "pkg-config"
]

[phases.install]
cmds = [
  # Ensure /usr/bin/python exists (yt-dlp-exec postinstall)
  "if [ -x /usr/bin/python3 ] && [ ! -e /usr/bin/python ]; then ln -s /usr/bin/python3 /usr/bin/python; fi",
  # Install Node deps without dev packages for prod
  "npm ci --omit=dev"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "22"