# Nixpacks configuration for Railway deployment

[phases.setup]
# System and build dependencies (canvas, ffmpeg)
apkPkgs = [
  "ffmpeg",
  "curl",
  "build-base",
  "cairo-dev",
  "pango-dev",
  "libjpeg-turbo-dev",
  "giflib-dev",
  "pixman-dev",
  "pkgconf"
]

[phases.install]
cmds = [
  # Install Node deps without dev packages for prod
  "npm ci --omit=dev"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "22"