# Nixpacks configuration for Railway deployment
# Using shell script to properly handle Python virtual environment

[providers]
nodejs = "18"

[phases.setup]
aptPkgs = ["ffmpeg", "python3", "python3-pip", "python3-venv", "curl"]

[phases.install]
cmds = [
  "npm ci",
  "bash -c 'python3 -m venv /opt/yt-dlp-venv && source /opt/yt-dlp-venv/bin/activate && pip install yt-dlp && ln -sf /opt/yt-dlp-venv/bin/yt-dlp /usr/local/bin/yt-dlp'"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 