# Nixpacks configuration for Railway deployment
# This ensures yt-dlp, ffmpeg, and Python are available

[providers]
nodejs = "18"

[phases.setup]
aptPkgs = ["ffmpeg", "python3", "python3-pip", "python3-venv", "curl"]

[phases.install]
cmds = [
  "npm ci",
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install yt-dlp",
  "ln -sf /opt/venv/bin/yt-dlp /usr/local/bin/yt-dlp"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 