# Nixpacks configuration for Railway deployment
[providers]
nodejs = "22"

[phases.setup]
# System and build dependencies (canvas, ffmpeg, yt-dlp)
apkPkgs = [
  "ffmpeg",
  "curl",
  "python3",
  "build-base",
  "cairo-dev",
  "pango-dev",
  "libjpeg-turbo-dev",
  "giflib-dev",
  "pixman-dev",
  "pkgconf"
]

[phases.install]
cmds = [
  # Install Node deps without dev packages for prod
  "npm ci --omit=dev",

  # Fetch the standalone yt-dlp executable and make it runnable
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"