# Nixpacks configuration for Railway deployment
[providers]
nodejs = "18"

[phases.setup]
# lightweight system tools only
apkPkgs = ["ffmpeg", "curl", "python3"]  # python3 is needed to execute the binary

[phases.install]
cmds = [
  # 1. install node deps
  "npm ci",

  # 2. fetch the standalone yt-dlp executable and make it runnable
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
        -o /usr/local/bin/yt-dlp && chmod +x /usr/local/bin/yt-dlp"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd  = "npm start"

[variables]
NODE_ENV = "production"